// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANFudCPxf0xUN4cw77qKWMU_PXTToRD80',
    appId: '1:311073432007:web:af6828bc6ccc757ed0f9e2',
    messagingSenderId: '311073432007',
    projectId: 'atelia-d3aaf',
    authDomain: 'atelia-d3aaf.firebaseapp.com',
    storageBucket: 'atelia-d3aaf.firebasestorage.app',
    measurementId: 'G-RF2ZDY8W2Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRYe3TQXpmzjNVImXK-LlrmbY0dBxquQg',
    appId: '1:311073432007:android:ec741ca8058b348cd0f9e2',
    messagingSenderId: '311073432007',
    projectId: 'atelia-d3aaf',
    storageBucket: 'atelia-d3aaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD5275v3q3Wtb7qqqhJ9nPSY0mKrLrYDEY',
    appId: '1:311073432007:ios:95c7b33d0409a765d0f9e2',
    messagingSenderId: '311073432007',
    projectId: 'atelia-d3aaf',
    storageBucket: 'atelia-d3aaf.firebasestorage.app',
    iosBundleId: 'com.example.atella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD5275v3q3Wtb7qqqhJ9nPSY0mKrLrYDEY',
    appId: '1:311073432007:ios:95c7b33d0409a765d0f9e2',
    messagingSenderId: '311073432007',
    projectId: 'atelia-d3aaf',
    storageBucket: 'atelia-d3aaf.firebasestorage.app',
    iosBundleId: 'com.example.atella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANFudCPxf0xUN4cw77qKWMU_PXTToRD80',
    appId: '1:311073432007:web:dc654a85c98ecfacd0f9e2',
    messagingSenderId: '311073432007',
    projectId: 'atelia-d3aaf',
    authDomain: 'atelia-d3aaf.firebaseapp.com',
    storageBucket: 'atelia-d3aaf.firebasestorage.app',
    measurementId: 'G-SKEXFXMGVJ',
  );
}
