// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUd9-xZu-Dm_7agsdzl7dypm4wu_vN9Fo',
    appId: '1:1097482533368:web:fbaee85d14347023dafe0d',
    messagingSenderId: '1097482533368',
    projectId: 'atelia-123',
    authDomain: 'atelia-123.firebaseapp.com',
    storageBucket: 'atelia-123.firebasestorage.app',
    measurementId: 'G-WQQ3R7L3C2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBA-Lam4AKlAzn2A52nvKnTJVs3nmqytDs',
    appId: '1:1097482533368:android:181994ea31245a91dafe0d',
    messagingSenderId: '1097482533368',
    projectId: 'atelia-123',
    storageBucket: 'atelia-123.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHBgFN9CuXKe6YMzJu4gbF0imhhsylOnY',
    appId: '1:1097482533368:ios:d13f0e3e3a40273adafe0d',
    messagingSenderId: '1097482533368',
    projectId: 'atelia-123',
    storageBucket: 'atelia-123.firebasestorage.app',
    androidClientId: '1097482533368-53f3nhms6ngt7rie8t6or0ce0qgo3aaj.apps.googleusercontent.com',
    iosClientId: '1097482533368-2l5o6ku5bf3qubkutdjla9ildf7noi22.apps.googleusercontent.com',
    iosBundleId: 'com.example.atella',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHBgFN9CuXKe6YMzJu4gbF0imhhsylOnY',
    appId: '1:1097482533368:ios:d13f0e3e3a40273adafe0d',
    messagingSenderId: '1097482533368',
    projectId: 'atelia-123',
    storageBucket: 'atelia-123.firebasestorage.app',
    androidClientId: '1097482533368-53f3nhms6ngt7rie8t6or0ce0qgo3aaj.apps.googleusercontent.com',
    iosClientId: '1097482533368-2l5o6ku5bf3qubkutdjla9ildf7noi22.apps.googleusercontent.com',
    iosBundleId: 'com.example.atella',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUd9-xZu-Dm_7agsdzl7dypm4wu_vN9Fo',
    appId: '1:1097482533368:web:21651127b6c63624dafe0d',
    messagingSenderId: '1097482533368',
    projectId: 'atelia-123',
    authDomain: 'atelia-123.firebaseapp.com',
    storageBucket: 'atelia-123.firebasestorage.app',
    measurementId: 'G-D3FVN1L8RX',
  );

}