import 'package:atella/core/themes/app_fonts.dart';
import 'package:get/get.dart';
import 'package:flutter/material.dart';
import 'package:image_picker/image_picker.dart';
import 'package:atella/l10n/generated/app_localizations.dart';
import '../../../Data/api/openai_service.dart';
import '../../../Data/Models/tech_pack_model.dart';
import '../../../Data/Models/user_subscription.dart';
import '../../../services/firebase/edit/edit_data_service.dart';
import '../../../services/PaymentService/stripe_subscription_service.dart';
import '../../../services/PaymentService/subscription_callback_service.dart';
import '../Views/Widgets/techpack_limit_dialog.dart';

class TechPackDetailsController extends GetxController {
  final EditDataService _editDataService = EditDataService();
  final StripeSubscriptionService _subscriptionService =
      StripeSubscriptionService();

  // Helper to get localization
  AppLocalizations get _l10n => AppLocalizations.of(Get.context!)!;

  // Edit mode tracking
  final RxBool _isEditMode = false.obs;
  bool get isEditMode => _isEditMode.value;
  TechPackModel? _editingTechPack;
  // Materials & Fabrics
  final mainFabricController = TextEditingController();
  final secondaryMaterialsController = TextEditingController();
  final fabricPropertiesController = TextEditingController();

  // Colors
  final primaryColorController = TextEditingController();
  final alternateColorwaysController = TextEditingController();
  final pantoneController = TextEditingController();

  // Sizes & Measurements
  final sizeRangeController = TextEditingController();
  final measurementChartController = TextEditingController();
  final autogeneratedController = TextEditingController();
  final RxString measurementImagePath = ''.obs;
  final RxBool showMeasurementImage = true.obs;
  final RxBool showMeasurementText = true.obs;

  // Technical Details
  final accessoriesController = TextEditingController();
  final stitchingController = TextEditingController();
  final decorativeStitchingController = TextEditingController();

  // Labeling & Branding
  final logoPlacementController = TextEditingController();
  final labelsNeededController = TextEditingController();
  final qrCodeController = TextEditingController();
  final RxString labelImagePath = ''.obs;
  final RxBool showLabelImage = true.obs;
  final RxBool showLabelText = true.obs;

  // Packaging & Shipping
  final packagingTypeController = TextEditingController();
  final foldingInstructionsController = TextEditingController();
  final insertsController = TextEditingController();

  // Production Details
  final costPerPieceController = TextEditingController();
  final quantityController = TextEditingController();
  final deliveryDateController = TextEditingController();

  // Manufacturers
  final manufacturerCountryController = TextEditingController();
  final RxString selectedManufacturerCountry = ''.obs;

  // Block visibility
  final RxBool showColorsBlock = false.obs;
  final RxBool showSizesBlock = false.obs;
  final RxBool showTechnicalBlock = false.obs;
  final RxBool showLabelingBlock = false.obs;
  final RxBool showPackagingBlock = false.obs;
  final RxBool showProductionBlock = false.obs;
  final RxBool showManufacturersBlock = false.obs;

  // Image picker instance
  final ImagePicker _picker = ImagePicker();

  // Tech pack generation state
  final RxBool isGeneratingTechPack = false.obs;
  final RxList<String> generatedTechPackImages = <String>[].obs;
  final RxString selectedDesignImagePath = ''.obs;
  final RxString selectedDesignPrompt = ''.obs;
  Map<String, dynamic> designData = {};

  TechPackModel? get editingTechPack => _editingTechPack;

  @override
  void onInit() {
    super.onInit();
    _initializeWithArguments();
    _setupInputListeners();
  }
  
  void _setupInputListeners() {
    // Listen to measurement text changes - hide image upload when text is filled
    measurementChartController.addListener(() {
      if (measurementChartController.text.trim().isNotEmpty) {
        showMeasurementImage.value = false;
      } else if (measurementImagePath.value.isEmpty) {
        showMeasurementImage.value = true;
      }
    });
    
    // Listen to measurement image changes - hide text field when image is uploaded
    measurementImagePath.listen((imagePath) {
      if (imagePath.isNotEmpty) {
        showMeasurementText.value = false;
      } else if (measurementChartController.text.trim().isEmpty) {
        showMeasurementText.value = true;
      }
      checkSizesBlockComplete();
    });
    
    // Listen to label text changes - hide image upload when text is filled
    labelsNeededController.addListener(() {
      if (labelsNeededController.text.trim().isNotEmpty) {
        showLabelImage.value = false;
      } else if (labelImagePath.value.isEmpty) {
        showLabelImage.value = true;
      }
    });
    
    // Listen to label image changes - hide text field when image is uploaded
    labelImagePath.listen((imagePath) {
      if (imagePath.isNotEmpty) {
        showLabelText.value = false;
      } else if (labelsNeededController.text.trim().isEmpty) {
        showLabelText.value = true;
      }
      checkLabelingBlockComplete();
    });
  }

  @override
  void onReady() {
    super.onReady();
    // Clear any pending callbacks to prevent disposed controller issues
    SubscriptionCallbackService().clearCallback();
  }

  void _initializeWithArguments() {
    // Get arguments passed from generate tech pack screen
    final arguments = Get.arguments as Map<String, dynamic>?;
    if (arguments != null) {
      selectedDesignImagePath.value = arguments['selectedDesignUrl'] ?? '';
      selectedDesignPrompt.value = arguments['designPrompt'] ?? '';
      designData = arguments['designData'] ?? {};

      // Check for edit mode
      final isEditMode = arguments['editMode'] == true;
      if (isEditMode) {
        _isEditMode.value = true;
        _editingTechPack = arguments['techPackModel'] as TechPackModel?;
        print('Tech Pack Details: Edit mode detected');
        _loadExistingTechPackData();
      }

      print('Tech Pack Details initialized with:');
      final imagePathPreview = selectedDesignImagePath.value.isNotEmpty
          ? selectedDesignImagePath.value.length > 50
                ? '${selectedDesignImagePath.value.substring(0, 50)}...'
                : selectedDesignImagePath.value
          : 'No image path';
      print('Design Image: $imagePathPreview');
      print('Design Prompt: ${selectedDesignPrompt.value}');
      print('Design Data: $designData');
      print('Edit Mode: $isEditMode');
    }
  }

  Future<void> _loadExistingTechPackData() async {
    if (_editingTechPack == null) return;

    try {
      print('Loading existing tech pack data for: ${_editingTechPack!.id}');

      // Get complete edit data from Firebase
      final editData = await _editDataService.getTechPackEditData(
        _editingTechPack!.id,
      );

      if (editData != null) {
        final techPackDetails =
            editData['techPackDetails'] as Map<String, dynamic>;
        if (techPackDetails.isNotEmpty) {
          final parsedDetails = _editDataService.parseTechPackDetailsForEdit(
            techPackDetails,
          );
          _populateTechPackFields(parsedDetails);

          // Show all blocks in edit mode
          _showAllBlocks();

          Get.snackbar(
            _l10n.tpdEditMode,
            _l10n.tpdLoadingExistingTechPack,
            backgroundColor: Colors.black,
            colorText: Colors.white,
            snackPosition: SnackPosition.TOP,
            duration: const Duration(milliseconds: 1500),
          );
        }
      }
    } catch (e) {
      print('Error loading tech pack data: $e');
      Get.snackbar(
        _l10n.tpdNotice,
        _l10n.tpdStartingWithEmptyForm,
        backgroundColor: Colors.black,
        snackPosition: SnackPosition.TOP,
        colorText: Colors.white,
        duration: const Duration(milliseconds: 1500),
      );
    }
  }

  void _populateTechPackFields(Map<String, dynamic> techPackDetails) {
    print('🔍 ===== POPULATING TECH PACK FIELDS =====');
    print('Full tech pack details structure:');
    print('  Materials: ${techPackDetails['materials']}');
    print('  Sizes: ${techPackDetails['sizes']}');
    print('  Labeling: ${techPackDetails['labeling']}');
    print('=========================================');

    // Materials & Fabrics
    final materials =
        techPackDetails['materials'] as Map<String, dynamic>? ?? {};
    mainFabricController.text = materials['mainFabric'] ?? '';
    secondaryMaterialsController.text = materials['secondaryMaterials'] ?? '';
    fabricPropertiesController.text = materials['fabricProperties'] ?? '';

    // Colors
    final colors = techPackDetails['colors'] as Map<String, dynamic>? ?? {};
    primaryColorController.text = colors['primaryColor'] ?? '';
    alternateColorwaysController.text = colors['alternateColorways'] ?? '';
    pantoneController.text = colors['pantone'] ?? '';

    // Sizes & Measurements
    final sizes = techPackDetails['sizes'] as Map<String, dynamic>? ?? {};
    sizeRangeController.text = sizes['sizeRange'] ?? '';
    measurementChartController.text = sizes['measurementChart'] ?? '';
    measurementImagePath.value = sizes['measurementImage'] ?? '';

    print('📏 Measurement data from Firebase:');
    print('   measurementImage field exists: ${sizes.containsKey('measurementImage')}');
    print('   measurementImage value: ${sizes['measurementImage']}');

    // Technical Details
    final technical =
        techPackDetails['technical'] as Map<String, dynamic>? ?? {};
    accessoriesController.text = technical['accessories'] ?? '';
    stitchingController.text = technical['stitching'] ?? '';
    decorativeStitchingController.text = technical['decorativeStitching'] ?? '';

    // Labeling & Branding
    final labeling = techPackDetails['labeling'] as Map<String, dynamic>? ?? {};
    print('🏷️ Labeling data from Firebase:');
    print('   Raw labeling map: $labeling');
    print('   labelImage field exists: ${labeling.containsKey('labelImage')}');
    print('   labelImage value: ${labeling['labelImage']}');

    logoPlacementController.text = labeling['logoPlacement'] ?? '';
    labelsNeededController.text = labeling['labelsNeeded'] ?? '';
    labelImagePath.value = labeling['labelImage'] ?? '';
    qrCodeController.text = labeling['qrCode'] ?? '';

    print('🖼️ After loading - label image path: ${labelImagePath.value}');
    print('   Logo placement: ${logoPlacementController.text}');
    print('   Labels needed: ${labelsNeededController.text}');

    // Packaging & Shipping
    final packaging =
        techPackDetails['packaging'] as Map<String, dynamic>? ?? {};
    packagingTypeController.text = packaging['packagingType'] ?? '';
    foldingInstructionsController.text = packaging['foldingInstructions'] ?? '';
    insertsController.text = packaging['inserts'] ?? '';

    // Production Details
    final production =
        techPackDetails['production'] as Map<String, dynamic>? ?? {};
    costPerPieceController.text = production['costPerPiece'] ?? '';
    quantityController.text = production['quantity'] ?? '';
    deliveryDateController.text = production['deliveryDate'] ?? '';

    // Manufacturers
    final manufacturers =
        techPackDetails['manufacturers'] as Map<String, dynamic>? ?? {};
    manufacturerCountryController.text = manufacturers['country'] ?? '';
    selectedManufacturerCountry.value = manufacturers['country'] ?? '';

    update();
  }

  void _showAllBlocks() {
    // In edit mode, show all blocks
    showColorsBlock.value = true;
    showSizesBlock.value = true;
    showTechnicalBlock.value = true;
    showLabelingBlock.value = true;
    showPackagingBlock.value = true;
    showProductionBlock.value = true;
    showManufacturersBlock.value = true;
  }


  void checkMaterialsBlockComplete() {
    if (mainFabricController.text.isNotEmpty &&
        secondaryMaterialsController.text.isNotEmpty &&
        fabricPropertiesController.text.isNotEmpty) {
      showColorsBlock.value = true;
    }
  }

  void checkColorsBlockComplete() {
    if (primaryColorController.text.isNotEmpty &&
        alternateColorwaysController.text.isNotEmpty &&
        pantoneController.text.isNotEmpty) {
      showSizesBlock.value = true;
    }
  }

  void checkSizesBlockComplete() {
    // Check if size range is filled AND either measurement text OR image is provided
    bool hasMeasurementInput = measurementChartController.text.isNotEmpty || 
                               measurementImagePath.value.isNotEmpty;
    
    if (sizeRangeController.text.isNotEmpty && hasMeasurementInput) {
      showTechnicalBlock.value = true;
    }
  }

  void checkTechnicalBlockComplete() {
    // Only require essential fields - decorative stitching is optional
    if (accessoriesController.text.isNotEmpty &&
        stitchingController.text.isNotEmpty) {
      showLabelingBlock.value = true;
    }
  }

  void checkLabelingBlockComplete() {
    // Check if logo placement is filled AND either label text OR image is provided
    bool hasLabelInput = labelsNeededController.text.isNotEmpty || 
                         labelImagePath.value.isNotEmpty;
    
    if (logoPlacementController.text.isNotEmpty && hasLabelInput) {
      showPackagingBlock.value = true;
    }
  }

  void checkPackagingBlockComplete() {
    if (packagingTypeController.text.isNotEmpty &&
        foldingInstructionsController.text.isNotEmpty &&
        insertsController.text.isNotEmpty) {
      showProductionBlock.value = true;
    }
  }

  void checkProductionBlockComplete() {
    if (costPerPieceController.text.isNotEmpty &&
        quantityController.text.isNotEmpty &&
        deliveryDateController.text.isNotEmpty) {
      showManufacturersBlock.value = true;
    }
  }

  void checkManufacturersBlockComplete() {
    // Optional field - no further block needed
    // User can proceed to generate even if this is empty
  }

  /// Set the selected manufacturer country from the country picker
  void setManufacturerCountry(String country) {
    selectedManufacturerCountry.value = country;
    manufacturerCountryController.text = country;
  }

  Map<String, String> _collectReferenceImages() {
    Map<String, String> images = {};
    
    // Add selected design image (main reference)
    if (selectedDesignImagePath.value.isNotEmpty) {
      images['selectedDesign'] = selectedDesignImagePath.value;
      print('Added selected design image: ${selectedDesignImagePath.value.substring(0, 50)}...');
    }
    
    // Add measurement chart image if uploaded
    if (measurementImagePath.value.isNotEmpty) {
      images['measurementChart'] = measurementImagePath.value;
      print('Added measurement chart image: ${measurementImagePath.value.substring(0, 50)}...');
    }
    
    // Add label reference image if uploaded
    if (labelImagePath.value.isNotEmpty) {
      images['labelReference'] = labelImagePath.value;
      print('Added label reference image: ${labelImagePath.value.substring(0, 50)}...');
    }
    
    print('Total reference images collected: ${images.length}');
    return images;
  }

  Future<void> generateTechPackImages() async {
    // Subscription check is now handled by checkSubscriptionAndGenerate method
    // This method only handles the actual generation

    try {
      print('=== STARTING DETAILED TECH PACK GENERATION ===');
      isGeneratingTechPack.value = true;
      generatedTechPackImages.clear();

      final techPackDetails = _collectTechPackDetails();
      final referenceImages = _collectReferenceImages();

      print('Tech Pack Details: $techPackDetails');
      print('Design Data: $designData');
      print('Reference Images: $referenceImages');

      // Try different prompt approaches in order of preference
      Map<String, String> prompts;
      String approach = '';

      try {
        // First attempt: Full detailed prompts with three views
        approach = 'Detailed Three Views';
        prompts = await OpenAIService.generateTechPackPrompts(
          creativeBrief: designData['creativeBrief'] ?? {},
          refinedConcept: designData['refinedConcept'] ?? {},
          finalDetails: designData['finalDetails'] ?? {},
          techPackDetails: techPackDetails,
          selectedDesignPrompt: selectedDesignPrompt.value,
        );
      } catch (e) {
        try {
          // Second attempt: Advanced detailed with explicit positioning
          approach = 'Advanced Detailed Layout';
          print('Trying advanced detailed prompts...');
          prompts = OpenAIService.getAdvancedDetailedPrompts(
            techPackDetails,
            designData['creativeBrief'] ?? {},
          );
        } catch (e2) {
          try {
            // Third attempt: Detailed single view
            approach = 'Detailed Single View';
            print('Trying detailed single view prompts...');
            prompts = OpenAIService.getDetailedSingleViewPrompts(
              techPackDetails,
              designData['creativeBrief'] ?? {},
            );
          } catch (e3) {
            // Final fallback: Simplified but detailed
            approach = 'Simplified Detailed';
            print('Using simplified detailed prompts...');
            prompts = OpenAIService.getSimplifiedDetailedPrompts(
              techPackDetails,
              designData['creativeBrief'] ?? {},
            );
          }
        }
      }

      print('Using approach: $approach');
      print('Manufacturing Prompt: ${prompts['manufacturing_prompt']}');
      print('Technical Prompt: ${prompts['technical_flat_prompt']}');

      // Generate manufacturing layout image with reference images
      print('Generating manufacturing layout image with ${referenceImages.length} reference images...');
      List<String> manufacturingImages = [];
      try {
        manufacturingImages = await OpenAIService.generateTechPackImages(
          prompt: prompts['manufacturing_prompt'] ?? '',
          referenceImages: referenceImages,
          numberOfImages: 1,
          size: '1024x1024',
        );
        print('✅ Manufacturing image generated successfully');
        print('   Base64 preview: ${manufacturingImages.isNotEmpty ? manufacturingImages[0].substring(0, 50) : "EMPTY"}...');
      } catch (e) {
        print('❌ Manufacturing image generation failed: $e');
        throw Exception('Failed to generate manufacturing image');
      }

      // Generate technical flat drawing with detailed approach and reference images
      print('Generating detailed technical flat drawing with ${referenceImages.length} reference images...');
      List<String> technicalImages = [];
      try {
        technicalImages = await OpenAIService.generateTechPackImages(
          prompt: prompts['technical_flat_prompt'] ?? '',
          referenceImages: referenceImages,
          numberOfImages: 1,
          size: '1024x1024', // Try 1024x1792 for vertical if 1024x1024 cuts off
        );
        print('✅ Technical flat drawing generated successfully');
        print('   Base64 preview: ${technicalImages.isNotEmpty ? technicalImages[0].substring(0, 50) : "EMPTY"}...');
      } catch (e) {
        print('❌ Technical image generation failed, trying fallback: $e');

        // Fallback with even simpler prompt
        final fallbackPrompt =
            'Technical flat drawing of garment, front view, black lines on white background. Include measurement labels A, B, C, D and construction details. Complete drawing centered with margins.';
        technicalImages = await OpenAIService.generateDesignImages(
          prompt: fallbackPrompt,
          numberOfImages: 1,
          size: '1024x1024',
        );
        print('   Fallback Base64 preview: ${technicalImages.isNotEmpty ? technicalImages[0].substring(0, 50) : "EMPTY"}...');
      }

      // CRITICAL CHECK: Verify images are different before adding to list
      if (manufacturingImages.isNotEmpty && technicalImages.isNotEmpty) {
        final areIdentical = manufacturingImages[0] == technicalImages[0];
        print('⚠️ COMPARING GENERATED IMAGES:');
        print('   Manufacturing: ${manufacturingImages[0].substring(0, 50)}...');
        print('   Technical: ${technicalImages[0].substring(0, 50)}...');
        print('   Are identical: $areIdentical');
        
        if (areIdentical) {
          print('❌ ERROR: AI generated IDENTICAL images for manufacturing and technical!');
          print('This is likely an OpenAI API issue or both prompts are too similar.');
        }
      }

      // Add images to the list
      generatedTechPackImages.addAll(manufacturingImages);
      generatedTechPackImages.addAll(technicalImages);
      
      print('📦 Final image list:');
      for (int i = 0; i < generatedTechPackImages.length; i++) {
        print('   Image[$i]: ${generatedTechPackImages[i].substring(0, 50)}...');
      }

      print('=== DETAILED TECH PACK GENERATION COMPLETED ===');
      print(
        'Generated ${generatedTechPackImages.length} tech pack images using: $approach',
      );

      // Increment techpack usage for STARTER plan users after successful generation
      await _subscriptionService.incrementTechpackUsage();

      // Validate and provide feedback
      if (generatedTechPackImages.length >= 2) {
        print(
          '✅ Both manufacturing and detailed technical images generated successfully',
        );
        Get.snackbar(
          _l10n.tpdSuccess,
          _l10n.tpdTechPackImagesGenerated,
          snackPosition: SnackPosition.TOP,
          backgroundColor: Colors.black,
          colorText: Colors.white,
          duration: const Duration(milliseconds: 1500),
        );
      } else {
        print(
          '⚠️ Warning: Only ${generatedTechPackImages.length} images generated',
        );
        Get.snackbar(
          _l10n.tpdPartialSuccess,
          _l10n.tpdSomeTechPackImagesGenerated,
          snackPosition: SnackPosition.TOP,
          backgroundColor: Colors.black,
          colorText: Colors.white,
        );
      }
    } catch (e) {
      print('=== TECH PACK GENERATION ERROR ===');
      print('Error: $e');

      Get.snackbar(
        _l10n.tpdError,
        _l10n.tpdFailedToGenerateTechPack(e.toString()),
        snackPosition: SnackPosition.TOP,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    } finally {
      isGeneratingTechPack.value = false;
    }
  }

  // Add this function to test different technical drawing approaches
  void testTechnicalDrawingPrompts() {
    final techPackDetails = _collectTechPackDetails();
    final creativeBrief = designData['creativeBrief'] ?? {};

    print('=== TESTING TECHNICAL DRAWING PROMPTS ===');

    // Test detailed three views
    final detailed = OpenAIService.getAdvancedDetailedPrompts(
      techPackDetails,
      creativeBrief,
    );
    print('Advanced Detailed: ${detailed['technical_flat_prompt']}');

    // Test single detailed view
    final singleView = OpenAIService.getDetailedSingleViewPrompts(
      techPackDetails,
      creativeBrief,
    );
    print('Single Detailed: ${singleView['technical_flat_prompt']}');

    // Test simplified detailed
    final simplified = OpenAIService.getSimplifiedDetailedPrompts(
      techPackDetails,
      creativeBrief,
    );
    print('Simplified Detailed: ${simplified['technical_flat_prompt']}');
  }

  // Gallery functionality for measurements
  Future<void> openCameraForMeasurement() async {
    try {
      final XFile? image = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 80,
      );

      if (image != null) {
        measurementImagePath.value = image.path;
        checkSizesBlockComplete();
      }
    } catch (e) {
      Get.snackbar(
        _l10n.tpdError,
        _l10n.tpdFailedToPickImage(e.toString()),
        snackPosition: SnackPosition.TOP,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    }
  }

  // Optional: Method to pick from gallery as alternative
  Future<void> pickImageFromGallery() async {
    try {
      final XFile? image = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 80,
      );

      if (image != null) {
        measurementImagePath.value = image.path;
        checkSizesBlockComplete();
      }
    } catch (e) {
      Get.snackbar(
        _l10n.tpdError,
        _l10n.tpdFailedToPickImage(e.toString()),
        snackPosition: SnackPosition.TOP,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    }
  }

  // Gallery functionality for labels
  Future<void> openCameraForLabels() async {
    try {
      final XFile? image = await _picker.pickImage(
        source: ImageSource.gallery,
        imageQuality: 80,
      );

      if (image != null) {
        labelImagePath.value = image.path;
        checkLabelingBlockComplete();
      }
    } catch (e) {
      Get.snackbar(
        _l10n.tpdError,
        _l10n.tpdFailedToPickImage(e.toString()),
        snackPosition: SnackPosition.TOP,
        backgroundColor: Colors.red,
        colorText: Colors.white,
      );
    }
  }

  Future<void> checkSubscriptionAndGenerate() async {
    // Check subscription before generating final techpack (with monthly reset check)
    bool canGenerate = await _subscriptionService.canUsePremiumFeatureWithReset('techpack');
    
    if (!canGenerate) {
      // Show upgrade prompt
      _showUpgradeDialog();
      return;
    }
    
    // If user has permission, start generation and navigate immediately
    generateTechPackImages(); // Don't await - let it run in background
    Get.toNamed('/tech_pack_ready_screen'); // Navigate immediately to show generating state
  }

  void _showUpgradeDialog() async {
    // Get current subscription to show in dialog
    final subscription = await _subscriptionService
        .getCurrentUserSubscription();
    String currentPlan = subscription?.subscriptionPlan ?? 'FREE';

    // Show different dialogs based on plan
    if (currentPlan == 'FREE') {
      _showFreeUpgradeDialog(currentPlan);
    } else if (currentPlan == 'STARTER' || currentPlan == 'STARTER_YEARLY') {
      _showStarterLimitDialog(subscription);
    } else if (currentPlan == 'PRO' || currentPlan == 'PRO_YEARLY') {
      _showProLimitDialog(subscription);
    } else if (currentPlan == 'STUDIO' || currentPlan == 'STUDIO_YEARLY') {
      _showStudioLimitDialog(subscription);
    }
  }

  void _showFreeUpgradeDialog(String currentPlan) {
    Get.dialog(
      AlertDialog(
        shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(15)),
        title: Row(
          children: [
            Expanded(
              child: Text(
                _l10n.tpUpgradeRequired,
                style: sfpsTitleTextTextStyle18600.copyWith(color: Colors.red),
              ),
            ),
          ],
        ),
        content: SingleChildScrollView(
          child: Column(
            mainAxisSize: MainAxisSize.min,
            crossAxisAlignment: CrossAxisAlignment.start,
            children: [
              // Current plan info
              Container(
                width: double.infinity,
                padding: EdgeInsets.all(12),
                decoration: BoxDecoration(
                  color: Colors.white,
                  borderRadius: BorderRadius.circular(8),
                  border: Border.all(color: Colors.grey.shade300),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Expanded(
                          child: Text(
                            _l10n.tpDialogCurrentPlan(_getPlanDisplayName(currentPlan)),
                            style: ssTitleTextTextStyle14400.copyWith(
                              fontSize: 12,
                              color: Colors.black,
                              fontWeight: FontWeight.bold,
                            ),
                            textAlign: TextAlign.center,
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
              SizedBox(height: 16),
              Text(
                _l10n.tpDialogTechpackPremiumRequired,
                style: ssTitleTextTextStyle124003,
                textAlign: TextAlign.center,
              ),
            SizedBox(height: 12),
            Container(
              padding: EdgeInsets.all(12),
              decoration: BoxDecoration(
                color: Colors.white,
                border: Border.all(color: Colors.grey.shade300),
                borderRadius: BorderRadius.circular(8),
              ),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  Text(
                    _l10n.tpDialogChoosePlan,
                    style: ssTitleTextTextStyle14400.copyWith(
                      fontSize: 16,
                      fontWeight: FontWeight.bold,
                      color: Colors.black,
                    ),
                  ),
                  SizedBox(height: 8),
                  _buildFeatureItem(_l10n.tpDialogStarterPlanOption),
                  _buildFeatureItem(_l10n.tpDialogProPlanOption),
                  _buildFeatureItem(_l10n.tpDialogFeatureProfessionalPDF),
                  _buildFeatureItem(_l10n.tpDialogFeatureManufacturerDB),
                  _buildFeatureItem(_l10n.tpDialogFeatureUnlimited3D),
                ],
              ),
            ),
          ],
          ),
        ),
        actions: [
          TextButton(
            onPressed: () => Get.back(),
            child: Text(
              _l10n.tpMaybeLater,
              style: ssTitleTextTextStyle14400.copyWith(
                color: Colors.black,
                fontWeight: FontWeight.bold,
              ),
            ),
          ),
          ElevatedButton(
            onPressed: () {
              Get.back();

              // Set callback to refresh the UI state after subscription
              SubscriptionCallbackService().setOnSubscriptionSuccess(() {
                print('Subscription upgraded, TechPack UI refreshed');
              });

              // Navigate to subscription screen
              Get.toNamed(
                '/subscribe',
                arguments: {
                  'returnRoute': '/tech_pack_details_screen',
                  'showSuccessMessage': true,
                },
              );
            },
            style: ElevatedButton.styleFrom(
              backgroundColor: Colors.black,
              padding: EdgeInsets.symmetric(horizontal: 16, vertical: 12),
              shape: RoundedRectangleBorder(
                borderRadius: BorderRadius.circular(24),
              ),
            ),
            child: Text(
              _l10n.tpDialogUpgradeNow,
              style: ssTitleTextTextStyle14400.copyWith(
                color: Colors.white,
                fontWeight: FontWeight.bold,
              ),
              textAlign: TextAlign.center,
            ),
          ),
        ],
      ),
      barrierDismissible: false,
    );
  }

  void _showStarterLimitDialog(UserSubscription? subscription) {
    Get.dialog(
      TechpackLimitDialog(
        title: 'Techpack Limit Reached',
        message: 'You\'ve reached your monthly techpack generation limit.',
        isPaidUser: true,
        onGetExtraTechpacks: () {
          Get.back();
          _purchaseExtraTechpacks(1, 5.99);
        },
        onUpgradePlan: () {
          Get.back();

          // Set callback to refresh the UI state after subscription
          SubscriptionCallbackService().setOnSubscriptionSuccess(() {
            print('Subscription upgraded, TechPack UI refreshed');
          });

          // Navigate to subscription screen
          Get.toNamed(
            '/subscribe',
            arguments: {
              'returnRoute': '/tech_pack_details_screen',
              'showSuccessMessage': true,
            },
          );
        },
        onMaybeLater: () => Get.back(),
      ),
      barrierDismissible: false,
    );
  }

  void _showProLimitDialog(UserSubscription? subscription) {
    Get.dialog(
      TechpackLimitDialog(
        title: 'Techpack Limit Reached',
        message: 'You\'ve reached your monthly techpack generation limit.',
        isPaidUser: true,
        onGetExtraTechpacks: () {
          Get.back();
          _purchaseExtraTechpacks(1, 5.99);
        },
        onUpgradePlan: () {
          Get.back();

          // Navigate to subscription screen
          Get.toNamed(
            '/subscribe',
            arguments: {
              'returnRoute': '/tech_pack_details_screen',
              'showSuccessMessage': true,
            },
          );
        },
        onMaybeLater: () => Get.back(),
      ),
      barrierDismissible: false,
    );
  }

  void _showStudioLimitDialog(UserSubscription? subscription) {
    Get.dialog(
      TechpackLimitDialog(
        title: 'Techpack Limit Reached',
        message: 'You\'ve reached your monthly techpack generation limit.',
        isPaidUser: true,
        onGetExtraTechpacks: () {
          Get.back();
          _purchaseExtraTechpacks(1, 5.99);
        },
        onUpgradePlan: () {
          Get.back();

          // Navigate to subscription screen (Studio users can still see upgrade options)
          Get.toNamed(
            '/subscribe',
            arguments: {
              'returnRoute': '/tech_pack_details_screen',
              'showSuccessMessage': true,
            },
          );
        },
        onMaybeLater: () => Get.back(),
      ),
      barrierDismissible: false,
    );
  }

  Future<void> _purchaseExtraTechpacks(int count, double price) async {
    try {
      Get.snackbar(
        _l10n.tpdProcessing,
        _l10n.tpdProcessingYourPurchase,
        backgroundColor: Colors.black,
        colorText: Colors.white,
        snackPosition: SnackPosition.TOP,
      );

      bool success = await _subscriptionService.purchaseExtraTechpacks(count, price);

      if (success) {
        Get.snackbar(
          _l10n.tpdSuccessExclamation,
          _l10n.tpdAdditionalTechPacksAdded(count.toString()),
          backgroundColor: Colors.black,
          colorText: Colors.white,
          snackPosition: SnackPosition.TOP,
          duration: const Duration(milliseconds: 1500),
        );

        // After successful purchase, allow user to generate techpack
        generateTechPackImages();
        Get.toNamed('/tech_pack_ready_screen');
      } else {
        Get.snackbar(
          _l10n.tpdPurchaseFailed,
          _l10n.tpdUnableToProcessPurchase,
          backgroundColor: Colors.red,
          colorText: Colors.white,
          snackPosition: SnackPosition.TOP,
        );
      }
    } catch (e) {
      Get.snackbar(
        _l10n.tpdError,
        _l10n.tpdPurchaseError(e.toString()),
        backgroundColor: Colors.red,
        colorText: Colors.white,
        snackPosition: SnackPosition.TOP,
      );
    }
  }

  String _getPlanDisplayName(String plan) {
    switch (plan) {
      case 'FREE':
        return 'Free';
      case 'STARTER':
        return 'Starter (€14.99/month)';
      case 'STARTER_YEARLY':
        return 'Starter (€149.99/year)';
      case 'PRO':
        return 'Pro (€34.99/month)';
      case 'PRO_YEARLY':
        return 'Pro (€349.99/year)';
      case 'STUDIO':
        return 'Studio (€79.99/month)';
      case 'STUDIO_YEARLY':
        return 'Studio (€799.99/year)';
      default:
        return 'Free';
    }
  }



  Widget _buildFeatureItem(String text) {
    return Padding(
      padding: EdgeInsets.only(bottom: 4),
      child: Row(
        children: [
          Icon(Icons.check_circle, color: Colors.green, size: 16),
          SizedBox(width: 8),
          Expanded(child: Text(text, style: ssTitleTextTextStyle124003)),
        ],
      ),
    );
  }

  // Collect all current tech pack details from form inputs
  Map<String, dynamic> _collectTechPackDetails() {
    return {
      'materials': {
        'mainFabric': mainFabricController.text,
        'secondaryMaterials': secondaryMaterialsController.text,
        'fabricProperties': fabricPropertiesController.text,
      },
      'colors': {
        'primaryColor': primaryColorController.text,
        'alternateColorways': alternateColorwaysController.text,
        'pantone': pantoneController.text,
      },
      'sizes': {
        'sizeRange': sizeRangeController.text,
        'measurementChart': measurementChartController.text,
        'measurementImage': measurementImagePath.value,
      },
      'technical': {
        'accessories': accessoriesController.text,
        'stitching': stitchingController.text,
        'decorativeStitching': decorativeStitchingController.text,
      },
      'labeling': {
        'logoPlacement': logoPlacementController.text,
        'labelsNeeded': labelsNeededController.text,
        'labelImage': labelImagePath.value,
        'qrCode': qrCodeController.text,
      },
      'packaging': {
        'packagingType': packagingTypeController.text,
        'foldingInstructions': foldingInstructionsController.text,
        'inserts': insertsController.text,
      },
      'production': {
        'costPerPiece': costPerPieceController.text,
        'quantity': quantityController.text,
        'deliveryDate': deliveryDateController.text,
      },
      'manufacturers': {
        'country': manufacturerCountryController.text,
      },
    };
  }

  @override
  void onClose() {
    mainFabricController.dispose();
    secondaryMaterialsController.dispose();
    fabricPropertiesController.dispose();
    primaryColorController.dispose();
    alternateColorwaysController.dispose();
    pantoneController.dispose();
    sizeRangeController.dispose();
    measurementChartController.dispose();
    accessoriesController.dispose();
    stitchingController.dispose();
    decorativeStitchingController.dispose();
    logoPlacementController.dispose();
    labelsNeededController.dispose();
    qrCodeController.dispose();
    packagingTypeController.dispose();
    foldingInstructionsController.dispose();
    insertsController.dispose();
    costPerPieceController.dispose();
    quantityController.dispose();
    deliveryDateController.dispose();
    manufacturerCountryController.dispose();
    super.onClose();
  }
}